### ISSUE TITLE
Add Issue Templates to all the repos

### ISSUE THREAD

**Issue by Wolftousen** [liatrio/liatrio-react-dora#82]
This needs to be done in all repos:

https://github.com/liatrio/backstage-liatrio-dora-plugin
https://github.com/liatrio/liatrio-react-dora
https://github.com/liatrio/liatrio-dora-api

**Comment by nsshaddox** [comment]
---
name: Bug Report
about: Create a report to help us improve
title: ''
labels: bug
assignees: ''

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Anonymized Data**
If possible, please provide any relevant data that has been anonymized to help us replicate the issue.

**Additional context**
Add any other context about the problem here.

**Comment by nsshaddox** [comment]
---
name: Feature Request
about: Suggest an idea for this project
title: ''
labels: enhancement
assignees: ''

---

**Is your feature request related to a problem? Please describe.**
A clear and concise description of the problem or issue.

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by nsshaddox** [comment]
@Wolftousen Was this what you were thinking?

**Comment by Wolftousen** [comment]
Those look good to me, but for Bugs at least, we'll also need to be supplied some data that's been anonymized to replicate
